# Site settings
title: "Rise of the Robotariat"
email: support@eye4games.com
description: > # this means to ignore newlines until "baseurl:"
  Get ready to rise up.
baseurl: "http://rise.eye4games.com" # the subpath of your site, e.g. /blog/
twitter_username: Eye4Games
github_username:  Eye4Games

# Build settings
markdown: kramdown
